[package]
name = "pillowimage"
version = "0.0.1"
authors = ["Peter Jin <peterhaijin@gmail.com>"]

[lib]
name = "pillowimage"
path = "src/lib.rs"

[build-dependencies]
bindgen = "*"
cc = "*"
walkdir = "*"

[dependencies]
lazy_static = "*"
